### ISSUE TITLE
An internal error occurred during: "Launching twitch".

### ISSUE THREAD

**Issue by sausagefngrs** [bhb27/smarttv-twitch#14]
I am certain I followed the instructions correctly, however, when doing the last step "Run as > 1 Tizen wen Application," I get the following error:

```
An internal error occurred during: "Launching twitch".
org.tizen.web.editor.configuration.TizenConfiguratorImpl cannot be cast to org.tizen.web.editor.configuration.IMobileConfigurator
```

Im trying to install on a Sarif (ULS001F).
Thanks for the help!

**Comment by bhb27** [comment]
I never see that bug or have that TV.

You will need to share more.

Screenshots of the problem, the log files
here they are in:
/tizen-studio-data/ide/logs/

But I'm on linux system.

Yours TV FW, computer OS, Tizen SDK/Studio version etc.

More info the better.

You will also have to search about it, as any search done by me you will have to test, so just search about that in genera.

Also try to start over delete the project in the Studio and try again.

**Comment by bhb27** [comment]
I don't think this is the problem.

I check the readme and I miss to inform that is need to install the **X.X TV** option on the main **b (Main SDK)**, were the only available option today is **4.0 TV**.

Because without that is not possible to create a TV project and not possible to correctly import the file system.

But once you have installed that **4.0 TV**, you can create a new TV project and after import the file system it automatic downgrade to version 2.4 and works very well.

At least here I have installed this app hundreds of time testing it I never have a problem, and from now and then I make a project from scratch and the change from 4.0 to 2.4 always happens...

I'm running latest version of Tizen SDK on ubuntu, if you guys have that problem, try to inform the TV model, Tizen OS  so I can see if I can try to reproduce here and add some better help on the readme.

The **About** option of the app can tell TV model and Tizen version, I think is also possible to get this info from Tizen device manager but my is not woring I fix it some other time and check it.

**Comment by brian91292** [comment]
@bhb27, well it fixed this exact issue for me, then I ran into another issue where Tizen Studio 2.x wouldn't allow me to execute any SSH commands on my TV, thus the need to downgrade to an old Tizen Studio version.

I'm on windows 10 enterprise (updates are currrent) and my TV is a UN40MU6300.

**Comment by bhb27** [comment]
I use win 10 in last January, it worked the same way for me.

But I did not had try after latest update of the sdk, I will try and post what I can find here.

**Comment by bhb27** [comment]
@sausagefngrs I manage to reproduce that error fix bellow.

I found the missing package

![sdk_3](https://user-images.githubusercontent.com/13755892/41305633-e47a0c16-6e49-11e8-852b-852d4663f1be.png)

I use latest studio

![screenshot from 2018-06-12 14-00-31](https://user-images.githubusercontent.com/13755892/41305651-f38dd4f8-6e49-11e8-848e-9de5b7807176.png)

Teste under latest Ubuntu and Win 10 version.

I update the README.md to included the bellow

## Tizen Package Manager(Installing the tools)

* Open **Tizen Package Manager** (on linux it may request you to use apt-get to install missing dependencies)
* Main tab **(Main SDK)** Install **4.0 TV**(or werever X.X TV version there is) and **Tizen SDK tools**,  **(on linux it may request you to use apt-get to install missing dependencies)**
* Second tab **(Extension SDK)** under **TV Extensions-4.0** install **Web app. Development**, install **Samsung Certificate Extension** and under **TV Extension Tools** install **Web app. Tools**


I also update it with images and etc info to help.

**Comment by bhb27** [comment]
If anyone has another related problem please reopen this or a new one...

**Comment by sausagefngrs** [comment]
Dude, thank you guys so much! Heroes!
