### ISSUE TITLE
Only top left corner of stream is shown

### ISSUE THREAD

**Issue by reconman** [bhb27/smarttv-twitch#2]
I wanted to find a better twitch app since the one provided in the app store does not offer user functionalities.

After installing the app, everything looks normal but when I start watching a stream, only the top left of the stream will be shown.

Device is UE40MU6179UXZG, latest version, computer is Windows 10, latest Tizen. I followed all your instructions as listed when installing the app.

**Comment by bhb27** [comment]
1/4 of the screen?
or how much

I can't understand this just by you telling me, so you need you to run the app as debug so I can see what may the app show in debug so we can start resolve this...

so in here the **Installation guide** below stemp
* Click on that folder BasicProject-tv-samsung-public-2.4 left click, then right click > Run as > 1 Tizen wen Application, the installation will start

instead of "**right click > Run as > 1 Tizen wen Application**", click on the top left corner "ladybug
" icon, and install the app as debug right after the app finish install will pop a new web browser window in the computer, on that will be the debug information...

on the app click OK, then wait the pop window load on the top bar click on console it will be probably empty, then just open a video, it will display some information wait the video finish load take a screen show or copy the content of the log post here.

 :+1:

**Comment by reconman** [comment]
Only 25 % is shown. The console does not say much:

![Console screenshot](http://puu.sh/yu7va/84d5c52c71.png)

**Comment by reconman** [comment]
Changing
`webapis.avplay.setDisplayRect(0, 0, 3840, 2160);`
to
`webapis.avplay.setDisplayRect(0, 0, 1920, 1080);`
fixed the issue, but this shows the image in 1080p instead of 4k.

**Comment by bhb27** [comment]
25% of the image? or 100% on 1/4 of the screen...

that info from the log is all that is needed for the start, are you shore that there inst more info after what you showed?
I expect a fail or something related that explains the result...

there is a problem related to yours TV I don't know way but there is
**[isUdPanelSupported](http://developer.samsung.com/tv/develop/api-references/samsung-product-api-references/productinfo-api)** only returns true if the tv is 4k and then the app config it self as 4k, the app is perfect here on a 4k 40" running the code form git...

instead of forcing set it as 1080p on the .js file change this line:
https://github.com/bhb27/smarttv-twitch/blob/tizen/widget.info#L2
to 

	Screen Resolution = 3840x2160

twitch doesn't have content above 1080p makes no diference today regarding that, but may there is a improve on how the image is scaleup...

let me know the result...
:+1:

**Comment by reconman** [comment]
All of the screen is filled with the top left 25 % of the screen. So I see the top left corner with 400 % zoom.

Changing the resolution in the widget.info file does nothing.

There are no logs after that, nothing that indicates an error.

When I click on the first div element on the page, it displays a size of 1920 x 1080 so it seems like the web UI is not displayed in 4k itself, only the video is.

Doing
```
tizen.systeminfo.getPropertyValue('DISPLAY', function(result) {
  console.log(result.resolutionWidth);
  console.log(result.resolutionHeight);
});
```
or
```
console.log(screen.height);
console.log(screen.width);
```

prints 1920x1080.

Setting <meta name="viewport" content="width=3840"> in the index.html shows the top left corner in the right position and size, but the rest of the image is black.

It doesn't even seem like Samsung supports app in 4k resolution. "http://tizen.org/feature/screen.size.normal.1080.1920" is the maximum value documented on the developer documentation.

**Comment by bhb27** [comment]
I'm running the app on a 4k tv no problem, so must be diference on how the firmware deal with that **setDisplayRect** function because I never had problem.

Even after setting

	setDisplayRect(0, 0, 3840, 2160);

the screens report as 1080p with makes no sense

I commit the above to proper deal with this type of problem and will take a long look on what can be done regarding this, probably samsung need to update the api, or we need to use something else, fortunately for this application this is not a problem today as the content above 1080p is not there

**Comment by bhb27** [comment]
I did some test regarding 4k playback

So I grab 4k a youtube video
https://www.youtube.com/watch?v=VAF4rfu-ETA

Grab it's 4k link stream play it on a computer player and check the resolution
![screenshot from 2017-12-17 13-08-40](https://user-images.githubusercontent.com/13755892/34080846-7ef4efb8-e32b-11e7-8c09-72373cc921aa.png)

Then I use the link to play the video on the twitch app and play the same video on youtube app

youtube
![yu](https://user-images.githubusercontent.com/13755892/34080860-9ef48652-e32b-11e7-9924-66c424dea6b1.jpg)

twitch
![tw](https://user-images.githubusercontent.com/13755892/34080862-a3e53a9e-e32b-11e7-9c54-477dfe36fb9e.jpg)

The pictures aren't screenshot are real pictures, so the brightness level is affected, but the pixel display is not,  comparing them doing a full zoom for me there ins't diference...

And reading the documentantion regarding **setDisplayRect** and some samsung forum related I believed it is supposed to be like this the result is there

You can test for yourself doing the above commit **4k test**, you can set the resolution to:

	SceneSceneChannel.mWebapisAvplay.setDisplayRect(0, 0, 3840, 2160);

or leave as it is 

	SceneSceneChannel.mWebapisAvplay.setDisplayRect(0, 0, screen.width, screen.height);

For me the visual result is the same, but my TV doenost have the bug that yours have when setting  **setDisplayRect(0, 0, 3840, 2160);**

bellow is the documentation... I will close this the day twitch has anything above 1080 if need any one can open a proper issue regarding any problem related to resolutions playback...

	setDisplayRect
	This method sets the display area for playing video content on TV screen. It should be called for showing video after calling open method. When all the value set as rect are set as 0, the Video Screen in the App disappears. Hide Function replacement.
	void setDisplayRect( long x, long y, long width, long height );
	Since : 1.0

	Parameters:

	x: Specifies the initial x-coordinate of display area in TV screen coordinates. This x value is smaller than TV screen width.
	y: Specifies the initial y-coordinate of display area in TV screen coordinates. This y value is smaller than TV screen height.
	width: The width of display area. This value is smaller than width of TV screen
	height: The height of display area from source image. This value is smaller than height of source image. If all members of display_rect is 0, video is hided
