### ISSUE TITLE
Stream doesn't load

### ISSUE THREAD

**Issue by saarsc** [bhb27/smarttv-twitch#3]
When I open the stream list I don't have a problem the stream list loads just fine 

But when I pick a stream to watch it says that it's loading (stuck on attempt 2 ) for a few seconds then the this line disappear and only the dots loading animation stays on screen and nothing will happen no matter how long I will keep the stream on 

I tried to reinstall and tried different versions of the twitch app I found on GitHub but all have the same problem

**Comment by bhb27** [comment]
You are not sharing necessary info "In doubt open a issue inform yours TV model, computer OS and problem"
As you can install just fine, start by sharing TV model.

**Comment by saarsc** [comment]
TV- ua43j5500
Computer - windows 10

And forgot to mention that everything worked fine until this week

**Comment by bhb27** [comment]
I explain on the [read.me](https://github.com/bhb27/smarttv-twitch#smarttv-twitch) 
"This branch is only dedicated for TV models from 2016 and up that run Tizen OS, if yours Smart Hub menu is different from the one below yours TV is probably not supported."

The original branch below may help
https://github.com/nikitakatchik/smarttv-twitch

That is the one that had support for those older model, but as I don't have a TV like that (series 5) I can't help on any problem related, simply because I can't test...

**Comment by saarsc** [comment]
Sorry thought my tv was newer 

Thank you for the help and sorry for the mistake

**Comment by bhb27** [comment]
No problem try the branch I share before maybe someone there that has the same series of TV can help..

:+1:
