### ISSUE TITLE
SAMSUNG M5500 issues

### ISSUE THREAD

**Issue by lukashenka** [bhb27/smarttv-twitch#6]
Hi

Thank you for you app

Have some troubles with SAMSUNG M5500
1. AddUser.handleKeyDown function doesn't work with condition AddUser.keyboardOn. All inputs goes to preventDefault.  Without it works fine
2. Chat window not working. Can't load from external source https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js (NETWORK_CONNECTION_TIMEOUT) in iframe nightdev.com. Only external loading js files failed. 

This problem explains in https://developer.tizen.org/ko/forums/web-application-development/problem-loading-external-page?langredirect=1

But in my cause adding 
<tizen:content-security-policy>self</tizen:content-security-policy>
to config.xml doesn't work. Console says is not policy as "self" exist

UPD: p.2 is WORKING. my network was with custom dns which not resolved googleapis.com :)

**Comment by bhb27** [comment]
I really don't get what you wanna to report regarding "1.". That is how I design the app

	 AddUser.keyBoardOn = true

Means the on screen keyboard is on, and on that moment, all key related goes to "AddUser.KeyboardEvent" pressing remote return key or on screen keyboard "Done or Cancel"  keys will close the on screen key board and give controls back to "AddUser.handleKeyDown", that is exactly what I intended there.

This behavior is restricted necessary for the perfect work of the app, because trying to switch screen when the keyboard in on can glitch the screen that you try to go to, if there ins't a loading screen first, eg go back to live (a screen that is always there so you can start a loading to it from another screen) from add a user or search screen when the on screen keyboard is showing glitches it.

Or you design a in app keyboard something like google has done to youtube app or you need that behavior, with is not a problem at all after all is so easy to dismiss the keyboard...

So do you really has a problem with the "1." you report? because I don't see one

I don't intent to design a in app key board as the one there works so well...

For "2.' I personalty only run on google dns, and no one ever reported that so I never see a problem like this, good to know that there is way and a fix...

If I miss something let me know.

**Comment by lukashenka** [comment]
Thank you for reply

I read code AddUser more deeply and see what you mean about 2 keyboard handles, one for global controls like channels (handleKeyDown), color buttons etc, other one (KeyboardEvent) for input to "#user_input" only

When keyboard is "ON"
![2018-02-05 12 50 34](https://user-images.githubusercontent.com/3519554/35798228-2e572ab6-0a73-11e8-82bb-16bde55b40c3.jpg)

1. I press center key on remote contoller on random letter. 
2. Keyboard event goes to handleKeyDown
3. flag AddUser.keyboardOn is true
4. handleKeyDown goes to event.preventDefault();
5. handleKeyDown is exit with return

6. Keyboard event goes to AddUser.KeyboardEvent
7. loadingData is false - goes to switch case
8. nothing match - going to default case then break
9. aaand nothing happens. Input form is empty

Solutions what can help
1. Remove preventDefault from p.4. Then event from keyboard (virtual) not aborts and  goes to input
2. Remove handleKeyDown eventListener when virtual keyboard is active and add it again when it's out. 

![2018-02-05 13 15 44](https://user-images.githubusercontent.com/3519554/35799546-2310cabe-0a77-11e8-8db7-4dff22fcd1c1.jpg)

That bug for my TV also occurs on Search.js. Removing preventDefault from listener solved problem.

**Comment by lukashenka** [comment]
For p.2 (about not working chat window) - its problem may occurs russian/cis  community which using ForkPlayer (iptv/torrent application) as dirty hack (replacing web content from some official web application  by using custom DNS). Anyway this problem is not necessary to solve. Posted just for information.

**Comment by bhb27** [comment]
That problem doesn't happens on a series 6 TV, samsung on they web site says that model M5500 is series 5, but if the app install it must be compatible...

So that may be a random bug that only affects some TV's...

I use yours detailed description on the above fix, please try and let me know the result....

As I explain on installation instruction, using the release_4_0_0.zip as a file system to install the app let the app to auto-update it self, now I assume you are not using that you are using the source files as a file system, so I recommend you do use the release on the long run...

:+1:

**Comment by lukashenka** [comment]
Just updated from master. It works well now. Thank you ;)

Your app must be more well-known. Googled twitch with chat for hour before find it
